import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { success: false, error: "Prompt is required." },
        { status: 400 }
      );
    }

    const lowerPrompt = prompt.toLowerCase();

    // Smart Schema Generator Logic
    let title = "Custom Pharma Form";
    let category = "General";
    let description = "Generated by Form Studio AI Assistant";
    let fields: any[] = [];
    let conditions: any[] = [];

    if (lowerPrompt.includes("dcr") || lowerPrompt.includes("doctor call") || lowerPrompt.includes("visit")) {
      title = "MR Daily Call Report (DCR) & Sampling";
      category = "Field Force Operations";
      description = "Comprehensive MR call report with doctor selection, discussion notes, sample quantity repeater, and live GPS stamp.";
      fields = [
        {
          id: "field_1",
          key: "doctor_name",
          label: "Doctor Name",
          type: "mappedTable",
          mappedTable: "Customer",
          mappedField: "partyName",
          required: true,
          section: "Doctor Details",
          order: 1,
        },
        {
          id: "field_2",
          key: "visit_date",
          label: "Visit Date & Time",
          type: "date",
          required: true,
          defaultValue: new Date().toISOString().split("T")[0],
          section: "Doctor Details",
          order: 2,
        },
        {
          id: "field_3",
          key: "gps_location",
          label: "Live GPS Location Stamp",
          type: "gps",
          required: true,
          section: "Verification Proof",
          order: 3,
        },
        {
          id: "field_4",
          key: "discussion_summary",
          label: "Discussion Summary & Brand Focus",
          type: "textarea",
          required: true,
          placeholder: "Key topics discussed with the doctor...",
          section: "Call Details",
          order: 4,
        },
        {
          id: "field_5",
          key: "samples_given",
          label: "Samples / POB Items Distributed",
          type: "repeaterTable",
          required: false,
          section: "Samples & POB",
          subFields: [
            { id: "sub_1", key: "product_name", label: "Product Name", type: "text", required: true, order: 1 },
            { id: "sub_2", key: "sample_qty", label: "Sample Qty", type: "number", required: true, order: 2 },
            { id: "sub_3", key: "pob_qty", label: "POB Order Qty", type: "number", required: false, order: 3 },
          ],
          order: 5,
        },
        {
          id: "field_6",
          key: "doctor_signature",
          label: "Doctor E-Signature Stamp",
          type: "signature",
          required: true,
          section: "Verification Proof",
          order: 6,
        },
      ];
    } else if (lowerPrompt.includes("feedback") || lowerPrompt.includes("survey") || lowerPrompt.includes("rating")) {
      title = "Doctor Brand Preference & Feedback Survey";
      category = "Marketing & Clinical Feedback";
      description = "Capture doctor ratings, product satisfaction, and brand feedback.";
      fields = [
        {
          id: "field_1",
          key: "doctor_name",
          label: "Doctor Name",
          type: "text",
          required: true,
          section: "Doctor Information",
          order: 1,
        },
        {
          id: "field_2",
          key: "specialty",
          label: "Specialty / Qualification",
          type: "select",
          options: ["Cardiologist", "Physician", "Pediatrician", "Gynecologist", "Dermatologist", "General Practitioner"],
          required: true,
          section: "Doctor Information",
          order: 2,
        },
        {
          id: "field_3",
          key: "efficacy_rating",
          label: "Product Efficacy Rating",
          type: "rating",
          required: true,
          section: "Brand Feedback",
          order: 3,
        },
        {
          id: "field_4",
          key: "prescribes_regularly",
          label: "Do you regularly prescribe our brand?",
          type: "radio",
          options: ["Yes", "No", "Occasionally"],
          required: true,
          section: "Brand Feedback",
          order: 4,
        },
        {
          id: "field_5",
          key: "feedback_comments",
          label: "Detailed Clinical Feedback / Suggestions",
          type: "textarea",
          required: false,
          placeholder: "Any observations or patient feedback...",
          section: "Brand Feedback",
          order: 5,
        },
      ];
    } else if (lowerPrompt.includes("expense") || lowerPrompt.includes("travel") || lowerPrompt.includes("claim")) {
      title = "MR Daily Travel & Expense Claim Form";
      category = "HR & Accounts";
      description = "Field expense claim for MR daily allowance, hotel bills, and travel receipts.";
      fields = [
        {
          id: "field_1",
          key: "mr_name",
          label: "MR Name",
          type: "mappedTable",
          mappedTable: "User",
          mappedField: "name",
          required: true,
          section: "Claimant Info",
          order: 1,
        },
        {
          id: "field_2",
          key: "claim_date",
          label: "Claim Date",
          type: "date",
          required: true,
          section: "Claimant Info",
          order: 2,
        },
        {
          id: "field_3",
          key: "travel_type",
          label: "Travel Category",
          type: "select",
          options: ["Local HQ", "Ex-Station", "Outstation"],
          required: true,
          section: "Travel Details",
          order: 3,
        },
        {
          id: "field_4",
          key: "expense_items",
          label: "Expense Itemized List",
          type: "repeaterTable",
          required: true,
          section: "Expense Items",
          subFields: [
            { id: "sub_1", key: "particulars", label: "Expense Particulars", type: "text", required: true, order: 1 },
            { id: "sub_2", key: "amount", label: "Amount (₹)", type: "number", required: true, order: 2 },
          ],
          order: 4,
        },
        {
          id: "field_5",
          key: "receipt_upload",
          label: "Upload Travel / Hotel Receipts (PDF/Image)",
          type: "fileUpload",
          required: true,
          section: "Bills & Proofs",
          order: 5,
        },
      ];
    } else {
      // Default Custom Prompt Generator
      title = prompt.split(" ").slice(0, 5).join(" ").toUpperCase() + " Form";
      category = "Custom";
      description = `AI-generated dynamic form based on: "${prompt}"`;
      fields = [
        {
          id: "field_1",
          key: "respondent_name",
          label: "Full Name",
          type: "text",
          required: true,
          section: "General Information",
          order: 1,
        },
        {
          id: "field_2",
          key: "contact_number",
          label: "Contact Mobile / Phone",
          type: "text",
          required: true,
          section: "General Information",
          order: 2,
        },
        {
          id: "field_3",
          key: "entry_date",
          label: "Entry Date",
          type: "date",
          required: true,
          defaultValue: new Date().toISOString().split("T")[0],
          section: "General Information",
          order: 3,
        },
        {
          id: "field_4",
          key: "details",
          label: "Specific Details / Notes",
          type: "textarea",
          required: false,
          placeholder: "Enter details as described in your prompt...",
          section: "Details",
          order: 4,
        },
        {
          id: "field_5",
          key: "verification_signature",
          label: "Verification Signature",
          type: "signature",
          required: false,
          section: "Signoff",
          order: 5,
        },
      ];
    }

    return NextResponse.json({
      success: true,
      formSchema: {
        title,
        category,
        description,
        accessMode: "Public",
        fields,
        conditions,
      },
    });
  } catch (err: any) {
    console.error("AI Form Generation API Error:", err);
    return NextResponse.json(
      { success: false, error: err.message || "Failed to generate form schema." },
      { status: 500 }
    );
  }
}
