import type { Metadata } from "next";

import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

import BootstrapClient from "@/components/BootstrapClient";

export const metadata: Metadata = {
  title: "Mabsol Pharma CRM",
  description: "Generated by Mabsol Infotech",

  icons: {
    icon: "/mabsol_logo.ico",
    shortcut: "/mabsol_logo.ico",
    apple: "/mabsol_logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}